In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
df=pd.read_csv('leaf.csv')

In [35]:
df

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0        w  120.362774  205.500000  119.395349  416.581395  20.676318
1        w  124.739583  202.800000  115.333333  354.333333  16.707151
2        w  134.691964  199.285714  116.857143  477.857143  22.496712
3        w  127.946309  178.368421   92.368421  278.473684  14.977453
4        w  135.431548  197.000000  112.690476  532.952381  17.604193
5        w  118.347962  226.150000  138.850000  608.900000  29.072797
6        w  135.436282  184.500000   95.142857  309.190476  13.055264
7        w  121.169643  226.000000  146.214286  595.571429  22.808542
8        w  131.127161  232.784314  144.588235  563.843137  11.948563
9        w  134.498092  210.212121  116.909091  594.848485  27.937685
10       w  131.164773  206.681818  114.727273  483.045455  22.903544
11       w  136.095960  201.400000  111.400000  444.600000  16.553622
12       w  122.631902  230.560976  142.195122  473.707317  24.521889
13       w  113.656180  213.107143  129.785714  480.857143  29.237766
14       w  133.894198  191.621622  115.513514  419.513513  17.489139
15       w  131.111498  213.666667  125.444444  537.888889  19.434819
16       w  127.835697  201.358491  116.509434  372.132075  23.929111
17       w  121.611260  199.744681  121.063830  338.127660  15.019107
18       w  106.242105  221.750000  140.000000  381.166667  18.903263
19       w  147.771127  220.111111  123.722222  479.166667  23.337037
20       w  135.823938  192.232877  115.095890  332.424658  12.805692
21       w  134.958974  226.673469  141.469388  435.959184  17.606107
22       w  128.531408  188.984000   93.312000  296.616000  16.932495
23       w  143.528736  170.363636   78.454545  400.000000  10.832306
24       w  141.109375  164.625000   68.000000  242.500000   6.753471
25       w  140.026030  189.896552   89.241379  561.310345  23.837590
26       w  132.587730  222.392157  133.058824  579.215686  19.832652
27       w  121.757895  174.000000   92.666667  217.777778  14.055446
28       w  135.677165  199.750000  105.208333  453.333333  16.185073
29       w  119.457404  180.741936   93.145161  227.774193  12.293254
...    ...         ...         ...         ...         ...        ...
4309     n  108.671171  208.571429   96.500000  438.428571  19.931515
4310     n  140.338631  202.884615   90.346154  310.692308  15.215950
4311     n  130.032641  299.369127  182.496644  513.771812  23.469295
4312     n  134.275424  200.533333   95.566667  220.216667  25.690135
4313     n  108.482639  369.000000  258.166667  472.666667  33.272027
4314     n  125.620172  299.033898  185.101695  304.050848  45.282642
4315     n  125.564466  366.862745  262.901961  473.901961  35.742430
4316     n  119.715024  216.795918   99.938776  452.176871  29.020238
4317     n  139.160396  235.000000  120.000000  253.812500  19.641688
4318     n  129.493820  204.947712   92.366013  382.640523  25.475827
4319     n  131.851923  328.547739  206.231156  310.648241  15.863861
4320     n  132.281508  189.761111   83.922222  336.180556  27.000565
4321     n  120.812009  224.589286  107.151786  578.232143  42.188984
4322     n  129.850394  285.750000  168.000000  371.750000  32.061464
4323     n  121.145480  231.481752  113.912409  460.364963  26.106539
4324     n  142.307018  206.655172  102.172414  524.896552  23.638931
4325     n  133.919304  174.300000   81.400000  213.300000   9.725450
4326     n  120.068966  206.648000   93.648000  441.536000  30.646491
4327     n  120.693452  216.047619   96.976190  336.619048  37.680488
4328     n  141.383940  257.440000  144.640000  343.360000  39.746240
4329     n  124.597015  349.500000  223.071429  421.952381  70.283234
4330     n  120.051968  488.120000  323.928000  561.936000  18.239695
4331     n  129.857500  333.840000  199.880000  485.160000  34.355786
4332     n  112.689049  533.063291  368.734177  525.063291  45.605591
4333     n  139.734592  200.690266   90.584071  450.884956  24.663350
4334     n  111

In [40]:
features=df.columns[1:].tolist()

In [41]:
features

['GLCM_pan', 'Mean_Green', 'Mean_Red', 'Mean_NIR', 'SD_pan']

In [42]:
x_train=df[features].values
y_train=df['class'].values

In [43]:
x_train

array([[120.3627737 , 205.5       , 119.3953488 , 416.5813953 ,
         20.67631835],
       [124.7395833 , 202.8       , 115.3333333 , 354.3333333 ,
         16.70715083],
       [134.6919643 , 199.2857143 , 116.8571429 , 477.8571429 ,
         22.49671178],
       ...,
       [132.1238592 , 465.34375   , 295.3333333 , 499.25      ,
         38.76296686],
       [124.4695364 , 215.1526316 ,  98.48421053, 675.9157895 ,
         28.50654248],
       [125.171928  , 559.048     , 365.968     , 439.272     ,
         15.39232155]])

In [44]:
y_train

array(['w', 'w', 'w', ..., 'n', 'n', 'n'], dtype=object)

In [45]:
df2=pd.read_csv('testing.csv')

In [46]:
df2

class    GLCM_pan   Mean_Green     Mean_Red     Mean_NIR     SD_pan
0       n  109.828571   183.700000    82.950000   251.750000  16.079412
1       n  130.284483   212.637931    96.896552   482.396552  21.210295
2       n  131.386555   185.466667    85.466667   419.666667  13.339998
3       n  141.345098   180.875000    81.500000   348.062500  18.213577
4       w  121.383408   218.357143   112.017857   426.607143  19.083196
5       n  122.757576   205.960000    86.760000   407.680000  17.823580
6       w  124.010204   215.594595   117.027027   477.297297  24.574628
7       w  125.608407   209.649123   121.228070   443.280702  25.757314
8       n  107.745833   204.133333    83.466667   479.866667  22.956965
9       n  140.203922   188.593750    84.437500   457.250000  30.193759
10      n  122.792453   199.740741   108.481482   384.740741  23.018906
11      n  117.427907   191.185185    86.555556   429.703704  24.765567
12      n  130.966357   256.352113   166.683099   506.964789  18.462242
13      n  132.678821   259.126984   170.341270   519.912698  23.550458
14      n  132.678821   259.126984   170.341270   519.912698  23.550458
15      n  133.752976   179.714286    85.238095   387.809524  19.732221
16      w  116.948953   214.562500   127.750000   390.208333  23.070506
17      w  116.948953   214.562500   127.750000   390.208333  23.070506
18      n  136.441799   214.041667   115.250000   579.416667  17.010413
19      w  125.074803   254.812500   147.500000   388.250000  20.224424
20      n  144.107807   186.941176    77.352941   468.411765  20.468391
21      w  121.094203   219.423077   122.423077   536.000000  30.714471
22      n  136.566667   196.388889    86.666667   364.666667  24.784379
23      n  115.891228   220.333333   103.472222   588.361111  25.091484
24      w  132.506944   206.370370   109.259259   532.962963  28.781424
25      n  121.064669   189.125000    92.575000   289.975000  14.142047
26      w  138.392265   200.235294   103.294118   431.411765  22.165312
27      n  124.080000   219.159091    98.250000   638.068182  22.000223
28      n  139.506749   231.156863   105.823529   780.784314  27.496055
29      n   99.159722   241.222222   116.777778   644.222222  34.628184
..    ...         ...          ...          ...          ...        ...
470     n  149.716216   253.071429   135.428571   319.142857  26.842796
471     n  135.904943   222.393939    98.818182   635.151515  32.129301
472     n  126.933472   193.540984    96.229508   270.557377  17.728733
473     n  134.956962   305.000000   176.320000   289.360000   9.795182
474     n  122.770206   184.750000    90.550000   218.000000  12.226610
475     n  138.525000   208.450000    90.750000   607.150000  43.524131
476     n  123.525630   234.780822   109.397260   767.397260  16.739334
477     n  122.798595   262.777778   129.407407   737.296296  26.681991
478     n  129.784114   261.290323   161.645161   405.161290  12.148406
479     n  117.109948  1848.916667  1594.583333  1597.333333  16.612412
480     n  141.306011   190.260870    92.043478   576.304348  20.342158
481     n  139.050810   210.017699   109.150443   248.309735  14.804609
482     n  127.230618   430.281250   293.645833   341.635417  12.076363
483     n  127.029581   180.714286    79.194805   171.935065  12.660559
484     n  115.222432   225.701492   106.567164   472.641791  13.556200
485     n  131.787703   237.703704   110.333333   722.166667  23.797298
486     n  127.531250   200.250000    82.750000   374.500000  20.197463
487     n  128.181522   244.680412   140.237113   414.608247  23.704575
488     n  125.428651   279.070175   189.166667   334.254386   8.140318
489     n  125.101695   245.066667   116.933333   681.800000  17.283775
490     n  129.424000   180.750000    86.000000   218.500000  12.036241
491     n  128.040752   237.850000   185.350000   275.200000  20.480723
492     n  119.971591   204.818182    98.000000   482.454545  41.877231
493     n  133.545346   234.811321   133.471

In [47]:
x_test=df2[features].values
y_test=df2['class'].values

In [50]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train) 
x_test_std=sc.transform(x_test)

In [51]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
accuracy=[] 
for i in range(1,11):   
    knn=KNeighborsClassifier(n_neighbors=i,p=2,metric='minkowski')   
    knn.fit(x_train_std,y_train)   
    y_pred_knn=knn.predict(x_test_std)   
    print('No of missclassified values for k={} is {}'.format(i,(y_test!=y_pred_knn).sum())) 
    print('Accuracy for K={} is {}'.format(i,accuracy_score(y_test,y_pred_knn)*100))    
    accuracy.append(accuracy_score(y_test,y_pred_knn)*100)

No of missclassified values for k=1 is 135
Accuracy for K=1 is 73.0
No of missclassified values for k=2 is 162
Accuracy for K=2 is 67.60000000000001
No of missclassified values for k=3 is 152
Accuracy for K=3 is 69.6
No of missclassified values for k=4 is 166
Accuracy for K=4 is 66.8
No of missclassified values for k=5 is 163
Accuracy for K=5 is 67.4
No of missclassified values for k=6 is 172
Accuracy for K=6 is 65.60000000000001
No of missclassified values for k=7 is 170
Accuracy for K=7 is 66.0
No of missclassified values for k=8 is 178
Accuracy for K=8 is 64.4
No of missclassified values for k=9 is 175
Accuracy for K=9 is 65.0
No of missclassified values for k=10 is 179
Accuracy for K=10 is 64.2


In [52]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=100,random_state=0,penalty='l1')
lr.fit(x_train_std,y_train)
y_pred_lr=lr.predict(x_test_std)
print('Misclassified Samples: %d'%(y_test!=y_pred_lr).sum())
print('Accuracy : %f'%(accuracy_score(y_test,y_pred_lr)))

/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Misclassified Samples: 143
Accuracy : 0.714000


In [53]:
from sklearn.metrics import confusion_matrix 
c =confusion_matrix(y_pred_lr, y_test)
print(c)

[[291 121]
 [ 22  66]]


In [54]:
from sklearn.model_selection import GridSearchCV
parameters = {
'C':[10, 20, 25, 50, 100, 200, 500],
'penalty':['l1','l2']
}

gsrf = GridSearchCV(estimator = lr, param_grid = parameters)
gsrf.fit(x_train_std, y_train)
print(gsrf.best_score_)
print(gsrf.best_params_)
print(gsrf.best_estimator_)
y_pred_lr_ht=gsrf.predict(x_test_std)

/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/l

/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9820235077206729
{'C': 100, 'penalty': 'l2'}
LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)


/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [56]:
print('Accuracy : %f'%(accuracy_score(y_test,y_pred_lr_ht)))

Accuracy : 0.708000


In [57]:
c =confusion_matrix(y_pred_lr_ht, y_test)
print(c)

[[291 124]
 [ 22  63]]


In [58]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(criterion='entropy',n_estimators=10,random_state=1)
forest.fit(x_train_std,y_train)
y_pred_rf=forest.predict(x_test)
print('misclassified samples:%d'%(y_test!=y_pred_rf).sum())
print('Accuracy : %f'%(accuracy_score(y_test,y_pred_rf)))

misclassified samples:187
Accuracy : 0.626000


In [59]:
from sklearn.metrics import confusion_matrix 
c =confusion_matrix(y_pred_rf, y_test)
print(c)

[[313 187]
 [  0   0]]


In [60]:
from sklearn.model_selection import GridSearchCV
parameters = {
    'criterion':['gini', 'entropy'],
    'n_jobs':[-1],
    'n_estimators':[15, 20, 25],
    'max_depth':[2, 3, 4, 5, 10]
}

gsrf = GridSearchCV(estimator = forest, param_grid = parameters)
gsrf.fit(x_train_std, y_train)
print(gsrf.best_score_)
print(gsrf.best_params_)
print(gsrf.best_estimator_)
y_pred_rf_ht=gsrf.predict(x_test_std)

/home/sasank/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


0.9914726895598064
{'criterion': 'entropy', 'max_depth': 10, 'n_estimators': 15, 'n_jobs': -1}
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=15, n_jobs=-1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)


In [61]:
print('Accuracy : %f'%(accuracy_score(y_test,y_pred_rf_ht)))

Accuracy : 0.768000


In [62]:
c =confusion_matrix(y_pred_rf_ht, y_test)
print(c)

[[310 113]
 [  3  74]]
